# Generated by Django 5.0.2 on 2024-06-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "identity",
                    models.IntegerField(
                        choices=[(1, "Type 1"), (2, "Type 2"), (3, "Type 3")]
                    ),
                ),
                ("email", models.EmailField(max_length=50)),
                ("user_name", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=16)),
            ],
        ),
    ]
