# Generated by Django 5.0.2 on 2024-06-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="identity",
            field=models.IntegerField(
                choices=[(1, "Type 1"), (2, "Type 2"), (3, "Type 3")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=50),
        ),
    ]
