# Generated by Django 5.0.2 on 2024-06-13 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0003_alter_user_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                ("notice_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=20, verbose_name="标题")),
                ("content", models.TextField(max_length=500, verbose_name="内容")),
                ("pic_url", models.CharField(max_length=100, verbose_name="图片链接")),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                ("priority", models.IntegerField(verbose_name="优先级")),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.user",
                        verbose_name="发布者",
                    ),
                ),
            ],
        ),
    ]
