# Generated by Django 5.0.2 on 2024-06-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OceanNuclearPollution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField()),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("date", models.DateField()),
            ],
        ),
    ]
