######################################################################
#
# File name : MULT_tb_compile.do
# Created on: Mon Mar 27 17:55:29 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modeltech_pe_10.4c\\win32pe\\vlib work
D:\\modeltech_pe_10.4c\\win32pe\\vlib msim

D:\\modeltech_pe_10.4c\\win32pe\\vlib msim/xil_defaultlib

D:\\modeltech_pe_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../exp1.srcs/sources_1/new/MULT.v" \
"../../../exp1.srcs/sources_1/new/MULT_tb.v" \


# compile glbl module
D:\\modeltech_pe_10.4c\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

