######################################################################
#
# File name : MULT_tb_wave.do
# Created on: Mon Mar 27 17:55:32 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
