# Generated by Django 4.2.2 on 2023-06-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INTERACT', '0004_creation_creation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='creation',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
