# Generated by Django 4.2.2 on 2023-06-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INTERACT', '0005_creation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='creation',
            name='comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creation',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creation',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creation',
            name='look',
            field=models.IntegerField(default=0),
        ),
    ]
