# Generated by Django 4.2.2 on 2023-06-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INTERACT', '0007_comment_type_like_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('target', models.CharField(max_length=20)),
                ('type', models.CharField(default='创作', max_length=20)),
            ],
        ),
    ]
