# Generated by Django 4.2.2 on 2023-06-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INTERACT', '0009_cdislike_clike_comment_dislike_comment_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(default='', max_length=20)),
                ('content', models.TextField()),
                ('is_read', models.CharField(default='未读', max_length=10)),
                ('type', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
