# Generated by Django 5.0.2 on 2024-06-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("class_name", models.CharField(max_length=50)),
                ("quantity", models.FloatField()),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("producer", models.CharField(max_length=20)),
                ("production_time", models.DateTimeField()),
                ("expiration_time", models.DateTimeField()),
                ("state", models.IntegerField(choices=[(0, "未售出"), (1, "已售出")])),
            ],
        ),
    ]
