######################################################################
#
# File name : DIV_tb_compile.do
# Created on: Sun Apr 02 16:34:20 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modeltech_pe_10.4c\\win32pe\\vlib work
D:\\modeltech_pe_10.4c\\win32pe\\vlib msim

D:\\modeltech_pe_10.4c\\win32pe\\vlib msim/xil_defaultlib

D:\\modeltech_pe_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../exp2.srcs/sources_1/new/DIV.v" \
"../../../exp2.srcs/sources_1/new/DIV_tb.v" \


# compile glbl module
D:\\modeltech_pe_10.4c\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

