######################################################################
#
# File name : DIV_tb_wave.do
# Created on: Sun Apr 02 16:34:23 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
