######################################################################
#
# File name : DIVU_tb.udo
# Created on: Sun Apr 02 16:33:02 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
