# Generated by Django 4.2.2 on 2023-06-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('favor_movie', models.CharField(max_length=100)),
                ('favor_novel', models.CharField(max_length=100)),
                ('favor_song', models.CharField(max_length=100)),
                ('admin_right', models.CharField(max_length=4)),
            ],
        ),
    ]
