# Generated by Django 4.2.2 on 2023-06-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INTERACT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creation',
            name='is_punish',
            field=models.CharField(max_length=10),
        ),
    ]
