# Generated by Django 4.2.2 on 2023-06-19 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INTERACT', '0002_alter_creation_is_punish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_inter',
        ),
    ]
