# Generated by Django 4.2.2 on 2023-06-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INTERACT', '0006_creation_comment_creation_dislike_creation_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.CharField(default='创作', max_length=20),
        ),
        migrations.AddField(
            model_name='like',
            name='type',
            field=models.CharField(default='创作', max_length=20),
        ),
    ]
