# Generated by Django 4.2.2 on 2023-06-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_pp', models.CharField(max_length=25)),
                ('user_ideas', models.IntegerField()),
                ('user_echo', models.IntegerField()),
                ('user_fan', models.IntegerField()),
                ('user_like', models.IntegerField()),
                ('user_concen', models.IntegerField()),
                ('user_coll', models.IntegerField()),
                ('user_generate', models.IntegerField()),
                ('user_gender', models.CharField(max_length=20)),
                ('user_age', models.IntegerField()),
                ('user_nature', models.CharField(max_length=20)),
                ('user_prefer', models.CharField(max_length=20)),
            ],
        ),
    ]
