# Generated by Django 4.2.2 on 2023-06-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='user_reply',
            field=models.IntegerField(default=0),
        ),
    ]
